#!/bin/bash
set -e

# Ensure XDG_RUNTIME_DIR is set
if [ -z "$XDG_RUNTIME_DIR" ]; then
  export XDG_RUNTIME_DIR="/tmp/runtime-root"
  mkdir -p $XDG_RUNTIME_DIR/pulse
  mkdir -p $XDG_RUNTIME_DIR/dconf
fi

# Grant root access to X server

xhost +local:root

# 1. Clean state (remove only containers, not volumes)
#echo "Bringing down any running containers (preserving volumes)..."
#COMPOSE_PROFILES=backend,frontend docker compose down --remove-orphans

# 2. Build
echo "Building base images..."
COMPOSE_PROFILES=backend,frontend docker compose build

# 3. Start up
echo "Starting up the stack using compose.yaml..."
COMPOSE_PROFILES=backend,frontend docker compose up

COMPOSE_PROFILES=backend,frontend docker compose down --remove-orphans
