#!/bin/bash
set -e

# Ensure XDG_RUNTIME_DIR is set
if [ -z "$XDG_RUNTIME_DIR" ]; then
  export XDG_RUNTIME_DIR="/tmp/runtime-root"
  mkdir -p $XDG_RUNTIME_DIR/pulse
  mkdir -p $XDG_RUNTIME_DIR/dconf
fi

# Ensure DISPLAY is set
if [ -z "$DISPLAY" ]; then
  export DISPLAY=:0
fi

# Ensure XDG_DATA_DIRS is set
if [ -z "$XDG_DATA_DIRS" ]; then
  export XDG_DATA_DIRS="/usr/local/share:/usr/share:/var/lib/snapd/desktop"
fi

xhost +local:root

# 1. Clean state (remove only containers, not volumes)
echo "Bringing down any running containers (preserving volumes)..."
COMPOSE_PROFILES=backend,frontend docker compose down --remove-orphans

# 2. Build
echo "Building base images..."
COMPOSE_PROFILES=backend,frontend docker compose build

# 3. Start up
echo "Starting up the stack using compose.yaml..."
COMPOSE_PROFILES=test docker compose up

COMPOSE_PROFILES=test docker compose down --remove-orphans
