#!/bin/bash
set -e

# 3. Start up
echo "Starting up the stack using compose.yaml..."
#COMPOSE_PROFILES=test docker compose up

docker compose --profile test build

sleep 1

docker compose --profile test up

sleep 1

docker compose down --remove-orphans
