name: CI - Pyicub Tests

on:
  push:
    branches:
      - CI  # Trigger only on push to the "CI" branch

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      COMPOSE_PROFILES: test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Run pyicub-test using Docker Compose
      run: |
        docker compose --profile test up --abort-on-container-exit pyicub-test

    - name: Upload test results if present
      if: success() || failure()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: docker/results/result.xml
